<template>
  <div id="app">
    <header class="header">
      <h1 class="title">Vue material checkbox</h1>
      <div class="flex">
      <a href="https://github.com/xrei/vue-material-checkbox"><button class="btn">Github</button></a>
      <a href="https://www.npmjs.com/package/vue-material-checkbox"><button class="btn">npm</button></a>
      </div>
    </header>
    <div class="example">
      <div class="flex">
        <div class="example-cont">
        <h2>Group check</h2>
          <div class="flex">
            <checkbox id="" value="cat" v-model="values" color="#f50057">Cat</checkbox>
            <checkbox id="" value="dog" v-model="values">Dog</checkbox>
            <checkbox id="" value="husky" v-model="values">Husky</checkbox>
            <checkbox id="" value="fish" v-model="values">fish</checkbox>
          </div>
          <span>{{ values }}</span>
        </div>
        <div class="example-code">
          <pre>
            <code class="html">
  &#x3C;checkbox value="cat" v-model="values" color="#f50057">Cat&#x3C;/checkbox&#x3E;
  &#x3C;checkbox value="dog" v-model="values">Dog&#x3C;/checkbox&#x3E;
  &#x3C;checkbox value="husky" v-model="values">Husky&#x3C;/checkbox&#x3E;
  &#x3C;checkbox value="fish" v-model="values">fish&#x3C;/checkbox&#x3E;
            </code>
          </pre>
        </div>
      </div>
      <p>There is no ID's on checkboxes and they will'be autogenerated, But i recommend specify them yourself.</p>
    </div>
    <br>
    <div class="example">
      <div class="flex">
        <div class="example-cont">
          <h2>Simple check/checked/disabled</h2>
          <div class="flex">
            <checkbox id="mycheckbox3" v-model="check2">{{ check2 }}</checkbox>
            <checkbox id="mycheckbox4" v-model="check3" checked>{{ check3 }}</checkbox>
            <checkbox id="mycheckbox5" v-model="check4" disabled>{{ check4 }}</checkbox>
          </div>
        </div>
        <div class="example-code">
          <pre>
            <code class="html">
  &#x3C;checkbox id="mycheckbox3" v-model="check2">{{ check2 }}&#x3C;/checkbox&#x3E;
  &#x3C;checkbox id="mycheckbox4" v-model="check3" checked>{{ check3 }}&#x3C;/checkbox&#x3E;
  &#x3C;checkbox id="mycheckbox5" v-model="check4" disabled>{{ check4 }}&#x3C;/checkbox&#x3E;
            </code>
          </pre>
        </div>
      </div>
    </div>
    <br>
    <footer>&copy; Roman 2017</footer>
  </div>
</template>

<script>
export default {
  name: 'app',
  data() { 
    return {
      check2: false,
      check3: false,
      check4: false,
      check5: false,
      check6: false,
      check7: false,
      values: []
    }
  }
}
</script>

<style lang="stylus">
*
  box-sizing: border-box
  margin: 0
  padding: 0
  &:before, &:after
    box-sizing: inherit

body, html
  width: 100%
  height: 100%
  color: #212121
  background-color: #263238
  font-family: 'Roboto'
  line-height: 1.5

a
  text-decoration: none

#app
  width: 62.5rem
  margin: 0 auto
  display: flex
  justify-content: flex-start
  flex-flow: column
  padding: 0 1rem 1rem
  @media screen and (max-width: 39.9375em)
    min-height: 100%
    width: 100%
    padding: 0 .75rem .75rem

header
  display: flex
  justify-content: center
  margin: 1.5rem
  flex-flow: column
  align-items: center
  .flex
    flex-flow: row

.title
  margin-bottom: 1rem
  text-align: center
  color: #fff

.example
  background-color: #fff
  border: 1px solid rgba(0,0,0, .05)
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2)
  padding: 1rem
  position: relative

  .example-cont
    width: 35%
    display: flex
    flex-flow: column

    .flex
      flex-flow: row
    h2
      margin-bottom: 1rem
      font-size: 20px
    @media screen and (max-width: 39.9375em)
      width: 100%

  .example-code
    position: relative
    display: flex
    justify-content: center
    align-items: center
    width: 65%
    @media screen and (max-width: 39.9375em)
      width: 100%
    pre
      width: 100%
      font-size: 14px
      overflow: scroll
      code
        padding: 1rem
.flex
  display: flex
  @media screen and (max-width: 39.9375em)
    flex-flow: column

footer
  display: flex
  justify-content: center
  align-items: center
  margin: 2rem 0 0
  color: #fff
  opacity: .4

.btn
  background-color: #00e5ff
  text-transform: uppercase
  align-items: center
  border-radius: 2px
  border: 0
  display: inline-flex
  height: 36px
  flex: 0 1 auto
  font-size: 16px
  font-weight: 500
  justify-content: center
  margin: .5rem
  min-width: 9rem
  outline: 0
  text-decoration: none
  transition: .3s cubic-bezier(.25,.8,.25,1), color 1ms
  position: relative
  vertical-align: middle
  cursor: pointer
  a
    text-decoration: none
    color: inherit
  &:focus, &:hover
    background-color: darken(#00e5ff, 5)
  &:active
    box-shadow: 0 5px 5px -3px rgba(0,0,0,.2), 0 8px 10px 1px rgba(0,0,0,.14), 0 3px 14px 2px rgba(0,0,0,.12)

</style>
