<template>
  <div id="app">
    <div class="title">
      <h1>Vue material checkbox</h1>
    </div>
    <div class="example">
      <div class="flex">
        <div class="example-cont">
        <h2>Group check</h2>
          <div class="flex">
            <checkbox id="" value="cat" v-model="values" color="#f50057">Cat</checkbox>
            <checkbox id="" value="dog" v-model="values">Dog</checkbox>
            <checkbox id="" value="husky" v-model="values">Husky</checkbox>
            <checkbox id="" value="fish" v-model="values">fish</checkbox>
          </div>
          <span>{{ values }}</span>
        </div>
        <div class="example-code">
          <pre>
            <code class="html">
  &#x3C;checkbox value="cat" v-model="values" color="#f50057">Cat&#x3C;/checkbox&#x3E;
  &#x3C;checkbox value="dog" v-model="values">Dog&#x3C;/checkbox&#x3E;
  &#x3C;checkbox value="husky" v-model="values">Husky&#x3C;/checkbox&#x3E;
  &#x3C;checkbox value="fish" v-model="values">fish&#x3C;/checkbox&#x3E;
            </code>
          </pre>
        </div>
      </div>
      <p>There is no ID's on checkboxes and they will'be autogenerated, But i recommend specify them yourself.</p>
    </div>
    <br>
    <br>
    <div class="example">
      <div class="flex">
        <div class="example-cont">
          <h2>Simple check/checked/disabled</h2>
          <div class="flex">
            <checkbox id="mycheckbox3" v-model="check2">{{ check2 }}</checkbox>
            <checkbox id="mycheckbox4" v-model="check3" checked>{{ check3 }}</checkbox>
            <checkbox id="mycheckbox5" v-model="check4" disabled>{{ check4 }}</checkbox>
          </div>
        </div>
        <div class="example-code">
          <pre>
            <code class="html">
  &#x3C;checkbox id="mycheckbox3" v-model="check2">{{ check2 }}&#x3C;/checkbox&#x3E;
  &#x3C;checkbox id="mycheckbox4" v-model="check3" checked>{{ check3 }}&#x3C;/checkbox&#x3E;
  &#x3C;checkbox id="mycheckbox5" v-model="check4" disabled>{{ check4 }}&#x3C;/checkbox&#x3E;
            </code>
          </pre>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="example">
      <div class="flex">
        <div class="example-cont">
          <h3>The checkbox is also resizable</h3>
          <div class="">
            <checkbox id="mycheckbox6" v-model="check5" style="font-size: 4rem;">{{ check5 }}</checkbox>
            <checkbox id="mycheckbox7" v-model="check6" style="font-size: 3rem;">{{ check6 }}</checkbox>
            <checkbox id="mycheckbox8" v-model="check7" style="font-size: 2rem;">{{ check7 }}</checkbox>
          </div>
        </div>
        <div class="example-code">
          <pre>
            <code class="html">
  &#x3C;checkbox id="mycheckbox6" v-model="check5" style="font-size: 4rem;">{{ check5 }}&#x3C;/checkbox&#x3E;
  &#x3C;checkbox id="mycheckbox7" v-model="check6" style="font-size: 3rem;">{{ check6 }}&#x3C;/checkbox&#x3E;
  &#x3C;checkbox id="mycheckbox8" v-model="check7" style="font-size: 2rem;">{{ check7 }}&#x3C;/checkbox&#x3E;
            </code>
          </pre>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  data() { 
    return {
      check2: false,
      check3: false,
      check4: false,
      check5: false,
      check6: false,
      check7: false,
      values: []
    }
  }
}
</script>

<style lang="scss">
*{
	box-sizing: border-box;
	margin: 0;
	padding: 0;
	&:before, &:after { box-sizing: inherit; }
}
body, html{
  width: 100%;
  height: 100%;
  color: #484848;
  background-color: #212121;
  font-family: 'Roboto';
}
#app{
  width: 62.5rem;
  margin: 0 auto;
  display: flex;
  justify-content: flex-start;
  flex-flow: column;
  padding: 1rem;
}

.title{
  margin-bottom: 1rem;
  text-align: center;
  color: #fff;
}

.example{
  background-color: #fff;
  border: 1px solid rgba(0,0,0, .05);
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
  padding: 1rem;
  position: relative;

  .example-cont{
    width: 33.33%;
    display: flex;
    flex-flow: column;
    h2{
      margin-bottom: 1rem;
      font-size: 20px;
    }
  }
  .example-code{
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    width: 66.66%;
    pre{
      width: 100%;
      font-size: 14px;
      overflow: scroll;
      code{
        padding: 1rem;
      }
    }
  }
}
.flex{
  display: flex;
}
</style>
